spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource-db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=localhost
eureka.instance.non-secure-port=${SERVER_PORT:8081}

aws.s3.bucket-name=${LOCALSTACK_S3_BUCKET_NAME:microservices}
aws.s3.region=us-east-1
aws.s3.endpoint=${LOCALSTACK_SERVER_URL:http://localhost:4566}
aws.s3.access-key=${LOCALSTACK_ACCESS_KEY:test}
aws.s3.secret-key=${LOCALSTACK_SECRET_KEY:test}

spring.rabbitmq.addresses=${RABBITMQ_SERVER_URL:localhost:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:welcome}

spring.cloud.stream.bindings.resource-uploaded-out-0.destination=resource-uploaded
spring.cloud.stream.bindings.resource-uploaded-out-0.content-type=application/json